Post.create(title: "Waiting for the man", body: "The Velvet Underground was an American rock band formed in New York City. First active from 1964 to 1973, its best-known members were Lou Reed and John Cale, who both went on to find success as solo artists.")
Post.create(title: "White Stripes", body: "\'Seven Nation Army\' is the first track on the album Elephant by American alternative rock band The White Stripes. It was released as a single in 2003 and is")
Tag.create(text: '90s')
Tag.create(text: '60s')
Tag.create(text: 'rock')

Post.find(1).tags << Tag.find(1)
Post.find(2).tags << Tag.find(2)
Post.find(1).tags << Tag.find(3)
Post.find(2).tags << Tag.find(3)